cetQueryApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^queryScore/', include('queryScore.urls', namespace="queryScore")),
]

queryScore/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<user_number>[0-9]+)/(?P<examtype>[a-zA-Z]+)/showpage/$', views.showpage, name='showpage'),
    url(r'^onQuery/$',views.onQuery, name='onQuery'),
    url(r'^onRegister$', views.onRegister, name='onRegister')

]

queryScore/models.py
from django.db import models

# Create your models here.
# The model for User table


class User(models.Model):
    number = models.CharField(max_length=40, primary_key=True)
    name = models.CharField(max_length=40)
    CET46exam = models.CharField(max_length=20, blank=True)
    NEEPexam = models.CharField(max_length=20, blank=True)
    PSCexam = models.CharField(max_length=20, blank=True)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.number

queryScore/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from .models import User
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def index(request):
    return render(request, 'queryScore/index.html')


def register(request):
    return render(request, "queryScore/register.html")


def showpage(request, user_number, examtype):
    user = get_object_or_404(User, pk=user_number)
    exam_number = ''
    if(examtype == "cet"):
        exam_number = user.CET46exam
    elif(examtype == "psc"):
        exam_number = user.PSCexam
    elif(examtype == "neep"):
        exam_number = user.NEEPexam
    else:
        raise Http404("非法访问")

    #查无此项
    if(exam_number==''):
        return render(request, "queryScore/index.html",{"errorMessage": "查询内容为空"})
    return render(request, "queryScore/showpage.html", {"user_number": user.number, "exam_number": exam_number})


# 查询提交
@csrf_exempt
def onQuery(request):
    user_number = request.POST["username"] #由于html设定的提交是username，但实际是提交的学号所以做出处理
    examtype = request.POST["selProvince"]

    #一级排错
    if(examtype==""):
        render(request, "queryScore/index.html",{"errorMessage":"请选择考试"})

    #user = get_object_or_404(User, pk=user_number)
    try:
        uesr = User.objects.get(pk=user_number)
    except User.DoesNotExist:
        return render(request,"queryScore/index.html", {"errorMessage":"学号没注册"})
    '''
    exam_number = ''
    if(examtype == "cet"):
        exam_number = user.CET46exam
    elif(examtype == "psc"):
        exam_number = user.PSCexam
    elif(examtype == "neep"):
        exam_number = user.NEEPexam
    else:
        raise Http404("非法访问")
    '''
    return HttpResponseRedirect(reverse('queryScore:showpage', args=(user_number, examtype,)))


#提交注册
@csrf_exempt
def onRegister(request):
    user_name = request.POST["username"]
    user_number = request.POST["password"]  #原html文件中此项name为password，为防止混淆故重命名为user_name
    examtype = request.POST["selProvince"]
    exam_number = request.POST["phone_number"]  #同上 为保持一致性

    # 一级排查:检查学号,准考证长度长度
    if(len(user_number)!=10):
        return render(request, "queryScore/register.html", {"errorMessage":"学号有误，请检查"})
    elif(examtype=='cet' and len(exam_number)!=15):
        return render(request, "queryScore/register.html", {"errorMessage":"四六级准考证长度为15位，请核准"})
    elif(examtype=='psc' and len(exam_number)!=13):
        return render(request, "queryScore/register.html",{"errorMessage":"普通话考试准考证长度为13位，请核准"})
    elif(examtype=='neep' and len(exam_number)!=15):
        return render(request, "queryScore/register.html",{"errorMessage":"研究生考试准考证长度为15位，请检查"})
    elif(examtype==""):
        return render(request, "queryScore/register.html",{"errorMessage":"未选择考试"})



    try:
        user = User.objects.get(pk=user_number)
    except User.DoesNotExist:
        user = User.objects.create(number=user_number, name=user_name)
    if(examtype=='cet'):
        user.CET46exam = exam_number
    elif(examtype=='psc'):
        user.PSCexam = exam_number
    elif(examtype=='neep'):
        user.NEEPexam = exam_number
    user.save()
    return HttpResponseRedirect(reverse('queryScore:index'))

queryScore/templates/queryScore/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static from staticfiles %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>准考证查询系统</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link rel="stylesheet" href="{% static "css/style.css" %}" />

<body>

<div class="login-container">
	<h1>准考证查询系统</h1>
	
	<div class="connect">
		<p>Link the world. Share to world.</p>
	</div>


    {% if errorMessage %}
        <p>{{ errorMessage }}</p>
    {% endif %}
	
	<form action="{% url 'queryScore:onQuery' %}" method="post" id="loginForm">
        {% csrf_token %}
		<div>
			<input type="text" name="username" class="username" maxlength="10"  placeholder="学号：" autocomplete="off"/>
		</div>
		<div>
			<select id = "selProvince" name="selProvince" class = "inputDiv"  id="考试类型" onChange="changeCity( )">  
		       <option value="">请选择
		      	</option>
		      	<option value="cet">英语四六级（含口试）
		      	</option>
		      	<option value="psc">普通话考试 PSC</option>
	            <option value="neep">研究生考试 NEEP</option>
        	</select><br>
		</div>

		
			<button id="submit" type="submit">查 询</button> 
			<!-- 按钮无法转入showpage -->
		
		
	</form>

	<a href="{% url "queryScore:register" %}">
		<button type="button" class="register-tis">还 没 有 绑 定 ？</button>
	</a>

</div>

<script src="{% static "js/jquery.min.js"%}"></script>
<script src="{% static "js/common.js" %}"></script>
<!--背景图片自动更换-->
<script src="{% static "js/supersized.3.2.7.min.js" %}"></script>
<script src="{% static "js/supersized-init.js" %}"></script>
<!--表单验证-->
<script src="{% static "js/jquery.validate.min.js" %}"></script>
<div class="connect" style="text-align:center;"><span>© 苏 应 印 象 工 作 室</span></div>
</body>
</html>

queryScore/templates/queryScore/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

{% load static from staticfiles %}

<title>准考证绑定页面</title>
<link rel="stylesheet" href="{% static "css/style.css" %}" />

<body>

<div class="register-container">
	<h1>准考证绑定系统</h1>
	
	<div class="connect">
		<p>Link the world. Share to world.</p>
	</div>

	<form action="{% url "queryScore:onRegister" %}" method="post" id="registerForm">
        {% csrf_token %}
        {% if errorMessage %}
            <P>{{errorMessage}}</P>
        {% endif %}
		<div>
			<input type="text" name="username" class="username" placeholder="请输入姓名" autocomplete="off"/>
		</div>

		<div>
			<input type="text" maxlength="10" name="password" class="password" placeholder="请输入学号" oncontextmenu="return false" onpaste="return false" />
		</div>
		
		<div>
	
		    <select id = "selProvince" name="selProvince" class = "inputDiv" onChange="changeCity( )">
		        <option value="">请选择</option>
		      	<option value="cet">英语四六级（含口试）</option>
		      	<option value="psc">普通话考试</option>
	            <option value="neep">研究生考试</option>
        	</select><br>
		</div>

		<div>
			<input type="text" maxlength="15" name="phone_number" class="phone_number" placeholder="请输入准考证号" autocomplete="off" id="number"/>
		</div>

		<div id="d1">
			<button id="submit" type="submit">绑 定 </button>
		</div>
		<!-- 按钮无法跳出弹出框 -->
      
	</form>
   
   <a href="{% url "queryScore:index" %}">
		<button type="button" class="register-tis">已 绑 定 ？ 点 此 查 询

		</button>
	
	<script type="text/javascript">
        $(function(){
            $('#d1').click(function(){
                alert('你点击了我');
            })
        })
    </script>
	</a>

</div>


<script src="{% static "js/jquery.min.js" %}"></script>
<!--<script src="{% static "js/common.js" %}"></script>-->
<!--背景图片自动更换-->
<script src="{% static "js/supersized.3.2.7.min.js" %}"></script>
<script src="{% static "js/supersized-init.js" %}"></script>
<!--表单验证-->
<script src="{% static "js/jquery.validate.min.js" %}"></script>
<div class="connect" style="text-align:center;"><span>© 苏 应 印 象 工 作 室</span></div>
</body>
</html>

queryScore/templates/queryScore/showpage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>准考证查询系统</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
{% load static staticfiles %}
<link rel="stylesheet" href="{% static "css/style.css" %}" />
<!--
<script type="text/javascript">
	function copyUrl2()
		{
		var Url2=document.getElementById("biao1");
		Url2.select(); // 选择对象
		document.execCommand("Copy"); // 执行浏览器复制命令
		alert("已复制好，可贴粘。");
		}
</script>
-->

<body>

<div class="login-container">
	<h1>准考证查询系统</h1>
	
	<div class="connect">
		<p>Link the world. Share to world.</p>
	</div>
	
	<form action="" method="post" id="loginForm">
    {% csrf_token %}
		<div>
			<input type="text" name="username" disabled="disabled" class="username" placeholder="学号：" autocomplete="\
			off" value="{{ user_number }}"/>
		</div>
		
		<div>
			<input cols="20" rows="10" id="biao1" disabled="disabled" placeholder="准考证：" value="{{ exam_number }}"/><br>
		</div>
		<!--
		<div id="d1">
			<button id="submit" type="button" onClick="copyUrl2()" value="点击复制代码">复 制 准 考 证</button>
		</div>
	    -->
		
	</form>


<div>
	<a href="http://cet.neea.edu.cn/cet/">
		<button type="button" class="register-tis">四 六 级 查 询 入 口 1</button>
	</a>
</div>
<div>

      <a href="http://www.chsi.com.cn/cet/">
		<button type="button" class="register-tis">四 六 级 查 询 入 口 2</button>
	
	  </a>
</div>	
<div>
       <a href="http://js.cltt.org/Web/Login/PSCP01001.aspx">
		<button type="button" class="register-tis">普 通 话 考 试 查 询 入 口</button>
	  </a>
</div>

<div>
      <a href="https://yz.chsi.com.cn/apply/cjcx/">
		<button type="button" class="register-tis">研 究 生 考 试 查 询 入 口</button>
	   </a>
</div>
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>
<!--背景图片自动更换-->
<script src="{% static "js/supersized.3.2.7.min.js" %}"></script>
<script src="{% static "js/supersized-init.js" %}"></script>
<!--表单验证-->
<script src="{% static "js/jquery.validate.min.js" %}"></script>

</div>

</body>
</html>